name: "git add a report if it has changed"
description: "The files are only added if there is no 'latest.<fileExtension>' file (or 'latest' dir) or if it has changed"
inputs:
  filePath:
    description: 'The path to the report file or dir'
    required: true
  destinationDir:
    description: 'The destination directory for the report type. Every report has to be in its own directory'
    required: true
  keepAllVersions:
    description: 'Whether to keep timestamped version if set to true. Otherwise only the latest version will be saved and overwritten.'
    default: 'true'
    required: false
  reportIsDirectory:
    description: 'Set to true if the report is not a file but a directory'
    default: 'false'
    required: false
  BUCKET_ACCESS_KEY_ID:
    description: "Access Key for the reports S3 Bucket"
    required: true
  BUCKET_SECRET_ACCESS_KEY:
    description: "Secret Access Key for the reports S3 Bucket"
    required: true
  BUCKET_ENDPOINT_URL:
    description: "Endpoint url for the reports S3 Bucket"
    default: "https://object.storage.eu01.onstackit.cloud/"
    required: false
  BUCKET_REGION:
    description: "Region for the reports S3 Bucket"
    default: "eu01"
    required: false
  BUCKET_NAME:
    description: "Name of the reports S3 Bucket"
    default: "ds-ris-reports-prod"
    required: false
runs:
  using: 'composite'
  steps:
    - name: Check that file path does not target a directory
      if: inputs.reportIsDirectory == 'false'
      shell: bash
      run: |
        if [ -d "${{ inputs.filePath }}" ]; then
          echo "File is a directory. Set input 'reportIsDirectory' to 'true'."
          exit 1
        fi
    - name: Check if report has changed (directory)
      shell: bash
      id: file-check-directory
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BUCKET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BUCKET_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ inputs.BUCKET_ENDPOINT_URL }}
        AWS_DEFAULT_REGION: ${{ inputs.BUCKET_REGION }}
      if: inputs.reportIsDirectory == 'true'
      run: |
        mkdir -p tmp/${{ inputs.destinationDir }}/latest
        aws s3 sync s3://${{ inputs.BUCKET_NAME }}/${{ inputs.destinationDir }}/latest tmp/${{ inputs.destinationDir }}/latest || true
        if diff -rq ${{ inputs.filePath }} tmp/${{ inputs.destinationDir }}/latest; then
          echo "Files are the same"
          echo "file_changed=false" >> $GITHUB_OUTPUT
        else
          echo "Files changed"
          echo "file_changed=true" >> $GITHUB_OUTPUT
        fi
    - name: Add latest report (directory)
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BUCKET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BUCKET_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ inputs.BUCKET_ENDPOINT_URL }}
        AWS_DEFAULT_REGION: ${{ inputs.BUCKET_REGION }}
      if: inputs.reportIsDirectory == 'true' && steps.file-check-directory.outputs.file_changed == 'true'
      run: |
        aws s3 sync ${{ inputs.filePath }} s3://${{ inputs.BUCKET_NAME }}/${{ inputs.destinationDir }}/latest --delete
    - name: Add timestamped report (directory)
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BUCKET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BUCKET_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ inputs.BUCKET_ENDPOINT_URL }}
        AWS_DEFAULT_REGION: ${{ inputs.BUCKET_REGION }}
      if: inputs.reportIsDirectory == 'true' && steps.file-check-directory.outputs.file_changed == 'true' && inputs.keepAllVersions == 'true'
      run: |
        NOW=$(TZ=Europe/Berlin date +'%Y-%m-%dT%H%M%S')
        aws s3 sync ${{ inputs.filePath }} s3://${{ inputs.BUCKET_NAME }}/${{ inputs.destinationDir }}/$NOW
    - name: Check if report has changed (file)
      shell: bash
      id: file-check-file
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BUCKET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BUCKET_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ inputs.BUCKET_ENDPOINT_URL }}
        AWS_DEFAULT_REGION: ${{ inputs.BUCKET_REGION }}
      if: inputs.reportIsDirectory == 'false'
      run: |
        extension=${${{ inputs.filePath }}##*.}
        mkdir -p tmp/${{ inputs.destinationDir }}
        aws s3 cp s3://${{ inputs.BUCKET_NAME }}/${{ inputs.destinationDir }}/latest.$extension tmp/${{ inputs.destinationDir }}/latest.$extension || true
        if [ -f tmp/${{ inputs.destinationDir }}/latest.$extension ] && cmp -s ${{ inputs.filePath }} tmp/${{ inputs.destinationDir }}/latest.$extension; then
          echo "Files are the same"
          echo "file_changed=false" >> $GITHUB_OUTPUT
        else
          echo "File changed"
          echo "file_changed=true" >> $GITHUB_OUTPUT
        fi
    - name: Add latest report (file)
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BUCKET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BUCKET_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ inputs.BUCKET_ENDPOINT_URL }}
        AWS_DEFAULT_REGION: ${{ inputs.BUCKET_REGION }}
      if: inputs.reportIsDirectory == 'false' && steps.file-check-file.outputs.file_changed == 'true'
      run: |
        extension=${${{ inputs.filePath }}##*.}
        aws s3 cp ${{ inputs.filePath }} s3://${{ inputs.BUCKET_NAME }}/${{ inputs.destinationDir }}/latest.$extension
    - name: Add timestamped report (file)
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BUCKET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BUCKET_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ inputs.BUCKET_ENDPOINT_URL }}
        AWS_DEFAULT_REGION: ${{ inputs.BUCKET_REGION }}
      if: inputs.reportIsDirectory == 'false' && steps.file-check-file.outputs.file_changed == 'true' && inputs.keepAllVersions == 'true'
      run: |
        NOW=$(TZ=Europe/Berlin date +'%Y-%m-%dT%H%M%S')
        extension=${${{ inputs.filePath }}##*.}
        aws s3 cp ${{ inputs.filePath }} s3://${{ inputs.BUCKET_NAME }}/${{ inputs.destinationDir }}/$NOW.$extension